set_property IOSTANDARD LVCMOS33 [get_ports {dynamic_addr[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dynamic_addr[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dynamic_addr[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dynamic_addr[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dynamic_addr[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dynamic_addr[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dynamic_addr[0]}]
set_property PACKAGE_PIN V10 [get_ports {dynamic_addr[6]}]
set_property PACKAGE_PIN U11 [get_ports {dynamic_addr[5]}]
set_property PACKAGE_PIN U12 [get_ports {dynamic_addr[4]}]
set_property PACKAGE_PIN H6 [get_ports {dynamic_addr[3]}]
set_property PACKAGE_PIN T13 [get_ports {dynamic_addr[2]}]
set_property PACKAGE_PIN R16 [get_ports {dynamic_addr[1]}]
set_property PACKAGE_PIN U8 [get_ports {dynamic_addr[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property PACKAGE_PIN J15 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN L16 [get_ports enable]
set_property IOSTANDARD LVCMOS33 [get_ports enable]
set_property PACKAGE_PIN C17 [get_ports i3c_scl]
set_property PACKAGE_PIN D18 [get_ports i3c_sda]
set_property IOSTANDARD LVCMOS33 [get_ports i3c_scl]
set_property IOSTANDARD LVCMOS33 [get_ports i3c_sda]
set_property IOSTANDARD LVCMOS33 [get_ports ready]
set_property PACKAGE_PIN H17 [get_ports ready]
set_property IOSTANDARD LVCMOS33 [get_ports rw]
set_property IOSTANDARD LVCMOS33 [get_ports scl]
set_property IOSTANDARD LVCMOS33 [get_ports sda]
set_property PACKAGE_PIN M13 [get_ports rw]
set_property PACKAGE_PIN D14 [get_ports scl]
set_property PACKAGE_PIN F16 [get_ports sda]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets scl_IBUF]

set_property MARK_DEBUG true [get_nets i3c_scl_OBUF]

set_property MARK_DEBUG true [get_nets slave/sda_i]
set_property MARK_DEBUG true [get_nets slave/sda_o]
set_property MARK_DEBUG true [get_nets master/sda_o]
set_property MARK_DEBUG true [get_nets master/sda_i]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 131072 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 1 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list i3c_scl_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list master/sda_i]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list slave/sda_i]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list master/sda_o]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list slave/sda_o]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]
